### ISSUE TITLE
AnsiColor weirdness with sh.git("log")

### ISSUE THREAD

**Issue by paul-hammant** [etianen/py.sh#34]
I can see ANSI color codes, but didn't expect to, for:

```
log = sh.git("log", "--pretty=oneline", "--no-color").stdout
print(log)
```

verification (Bash):

```
git log --pretty=oneline
# and 
git log --pretty=oneline --no-color
```

Seems Py.sh handing "--no-color" to git is having no effect :-(

**Comment by paul-hammant** [comment]
Wrong py.sh repo

**Comment by etianen** [comment]
Phew! I was very confused by the issue, but had snoozed it until I came
back from holiday.
